### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by sluukkonen** [sluukkonen/codec#49]
- [ ] Add missing codecs for built-in types (ignoring typed arrays for now)
  - [ ] `null`
  - [ ] `undefined`
  - [ ] `bigint`
  - [ ] `integer`
  - [ ] `set`
  - [ ] `map`
  - [ ] `true` / `false` (perhaps)
- [ ] Add missing combinators
  - [ ] `tuple`
  - [ ] `nullable`
  - [ ] `refinement`
  - [ ] `chain`
  - [ ] `lazy`
- [ ]  Add codecs for parsing data from a JSON-compatible input (how to name these?)
  - [ ] `bigintFromString`
  - [ ] `setFromArray`
  - [ ] `dateFromString`
  - [ ] `mapFromEntries`
- [ ] Add missing object combinators / convenience features
  - [ ] `pick` / `omit`
  - [ ] `intersection` / `merge`
  - [ ] `partial` (maybe)
- [ ] Add some structured way to validate the input values more carefully (minimum length, maximum length, value greater than, value less than etc.). Should work with built-in codecs like `string`, `array`, `number` etc.
- [ ] Do a polish pass on error messages
  - [ ] Decide on the set of built-in error types
  - [ ] Add human readable messages to errors
  - [ ] Add actual/expected values to error objects (or maybe the types of values)
- [ ] Test / fix tree shaking by adding necessary pure annotations
- [ ] Add more comprehensive benchmarks & tune performance accordingly
- [ ] Add property-based tests to test codec round tripping
- [ ] Add documentation 
- [ ] Try to write something like an JSON schema generator to try out the introspection capabilities

**Comment by japiirainen** [comment]
Regarding `missing codecs for built-in types `, is `integer` a built in JS type? I thought the only number types are `number` and `bigint`. I guess these could belong to the refinement category along `email`, `uuid`, `url`, etc...

This category could perhaps also include even more number types such as `natural` and `float`.

Thoughts?

**Comment by sluukkonen** [comment]
> Regarding `missing codecs for built-in types `, is `integer` a built in JS type? I thought the only number types are `number` and `bigint`. I guess these could belong to the refinement category along `email`, `uuid`, `url`, etc...
>

So far this document has been mostly been just a lightweight TODO list for me, so all the categorizations are a bit fast and loose at the moment. You're of course correct that `integer` could be in the refinement category.
 
> This category could perhaps also include even more number types such as `natural` and `float`.
> 
> Thoughts?

With naturals you have the problem of not knowing whether to start with 0 or 1, but I think something like could be useful, yes. Maybe call them `positiveInteger` and `nonNegativeInteger` or something.

What would a `float` codec check? How would it differ from the existing `number` codec?
